### PR TITLE
changing content to advise use of README

### LINKED ISSUE #36: Conflicting recommendations about text documentation
The recommendations pertaining to text documentation about the data are inconsistent. 

About "Keeping track of your analyses," [module 2, _Formatting data tables in Spreadsheets_](https://librarycarpentry.org/lc-spreadsheets/01-format-data/index.html) states:

> [K]eep track of the steps you took in your clean up or analysis. You should track these steps as a scientist would each step in an experiment. You can do this in another text file, or a good option is to create a new tab in your spreadsheet with your notes. This way the notes and data stay together.

About "Inclusion of metadata," [module 3, _Formatting problems_](https://librarycarpentry.org/lc-spreadsheets/02-common-mistakes/index.html) states: 

> Unlike a table in a paper or a supplemental file, metadata (in the form of legends) should not be included in a data file since this information is not data, and including it can disrupt how computer programs interpret your data file. Rather, metadata should be stored as a separate file in the same directory as your data file, preferably in plain text format with a name that clearly associates it with your data file.

While not referring to exactly the same documentation, both pieces of advice do refer to text documentation about the dataset rather than the data themselves. It seems like best practice would be to store documentation about the dataset in a single location.

### PR DESCRIPTION
**Pull request by jt14den**
fixes #36 by mirroring DataCarpentry ecology lesson recommended practice (using README to capture data prep) and not use note spreadsheet tab.
Still need to create screen shot on this one, so it is WIP.

### CODE REVIEW

**Comment by jt14den** [comment]
@morskyjezek Jesse, am still working on this one. Will add screen shot and make sure any references in later episodes are fixed. This might take a bit.

**Comment by morskyjezek** [comment]
This is great! We've had these on the to do list for a while. Thank you for working on it! The PR check indicates some of the files were not creating the markdown correctly, do you have any insights on that? I'll also try to take a look.

**Comment by jt14den** [comment]
@morskyjezek the workshop series finished last week, so i'm hoping to submit something this week. i wanted to get this PR draft started so I wouldn't forget.

**Comment by morskyjezek** [comment]
This looks like a good change to me, but do you have any additional information on why the build workflow failed? @jt14den

**Comment by morskyjezek** [comment]
It looks god when I run it locally.

**Pull request merged**
